### Listar todos os todos
GET http://localhost:3000/todos

### Criar um novo todo
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Treinar o rasengan",
  "userId": "1bc9e65b-7755-48ed-b341-6f37f7076018"
}

### Obter um todo específico
GET http://localhost:3000/todos/3993ee0d-2c0c-448f-9d5d-f7185a9d9429

### Atualizar um todo
PUT http://localhost:3000/todos/3993ee0d-2c0c-448f-9d5d-f7185a9d9429
Content-Type: application/json

{
  "title": "Comprar leite desnatado",
  "done": true
}

### Excluir um todo
DELETE http://localhost:3000/todos/3993ee0d-2c0c-448f-9d5d-f7185a9d9429

### Criar outro todo
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Fazer exercícios",
  "userId": 2
}

### Listar todos novamente para ver as mudanças
GET http://localhost:3000/todos
